"use strict";
require("./neon-query-cache");
const http=require("http"),crypto=require("crypto"),fs=require("fs"),path=require("path");
const original=http.createServer.bind(http), MARKET="802163", TZ="Europe/Berlin", LAT=51.90724, LON=8.61329;
let pg,initDone=false,runPromise=null;
function pool(){if(!pg){const{Pool}=require("pg");pg=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==="false"?false:{rejectUnauthorized:false}})}return pg}
async function init(){if(initDone)return;const p=pool();await p.query(`CREATE TABLE IF NOT EXISTS bakery_q15(market_code text,sale_date date,slot time,article_no text,article_name text,qty numeric,revenue numeric,PRIMARY KEY(market_code,sale_date,slot,article_no));CREATE TABLE IF NOT EXISTS bakery_daily(market_code text,sale_date date,article_no text,article_name text,qty numeric,revenue numeric,writeoff numeric,action_qty numeric,PRIMARY KEY(market_code,sale_date,article_no));CREATE TABLE IF NOT EXISTS bakery_mail(source_id text PRIMARY KEY,imported_at timestamptz default now());CREATE TABLE IF NOT EXISTS bakery_plans(market_code text,plan_date date,generated_at timestamptz default now(),source_max_date date,payload jsonb,weather jsonb,context jsonb,PRIMARY KEY(market_code,plan_date));CREATE TABLE IF NOT EXISTS bakery_actuals(market_code text,plan_date date,article_no text,interval_index int,planned_qty int,actual_qty int,done_at timestamptz default now(),PRIMARY KEY(market_code,plan_date,article_no,interval_index));CREATE TABLE IF NOT EXISTS bakery_jobs(job_key text PRIMARY KEY,ran_at timestamptz default now())`);initDone=true}
const n=s=>String(s||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g," ").trim();
const num=v=>{if(typeof v==="number")return Number.isFinite(v)?v:0;let s=String(v??"").trim();if(!s)return 0;if(s.includes(","))s=s.replace(/\./g,"").replace(",",".");const x=Number(s.replace(/[^0-9+.-]/g,""));return Number.isFinite(x)?x:0};
const iso=v=>{if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);let s=String(v||"").trim(),m=s.match(/^(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})$/);if(m){let y=+m[3];if(y<100)y+=2000;return `${y}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`}m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,"0")}-${m[3].padStart(2,"0")}`:""};
const article=v=>(String(v||"").match(/\b(\d{6,12})\b/)||[])[1]||"";
function slot(v){const m=String(v||"").match(/(\d{1,2}):?(\d{2})/);return m?`${m[1].padStart(2,"0")}:${m[2]}:00`:""}
function hk(v){const h=n(v);if(h==="kalendertag"||h==="datum")return"date";if(h.includes("viertelstunde"))return"slot";if(h==="artikel"||h.includes("artikelnummer"))return"article";if(h.includes("artikelbezeichnung")||h==="bezeichnung"||h==="artikelname")return"name";if(h==="menge")return"qty";if(h==="umsatz")return"revenue";if(h.includes("vollabschrift")||h.includes("abschrift"))return"writeoff";if(h.includes("aktion")&&h.includes("menge"))return"action";return""}
function berlin(){const a=new Intl.DateTimeFormat("en-CA",{timeZone:TZ,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()),o=Object.fromEntries(a.map(x=>[x.type,x.value]));return{date:`${o.year}-${o.month}-${o.day}`,hour:+o.hour,minute:+o.minute}}
function add(d,x){const z=new Date(d+"T12:00:00Z");z.setUTCDate(z.getUTCDate()+x);return z.toISOString().slice(0,10)}
function wd(d){return new Date(d+"T12:00:00Z").getUTCDay()}
function median(a){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function catalog(){const s=fs.readFileSync(path.join(__dirname,"public/backprognose.js"),"utf8"),m=s.match(/const REFERENCE_PLAN\s*=\s*(\[[\s\S]*?\]);\s*\n\s*const state/);return m?Function(`return (${m[1]})`)():[]}
const STOP=new Set("g gg b o bo harry preb prebake preback pb bake off bio e fs cl herzstucke herz schaefers schafers jude juede bakerm panobake deh h s ef afs ary europ filly csm topkauf brink edeka gut gunstig ca bv va kg st stk gramm geschnitten vorgeschnitten".split(" "));
function core(s){return n(s).replace(/nougatcr/g,"nougat").replace(/schokoladengla/g,"schokoladenglasur").replace(/crodots/g,"crodot").split(" ").filter(x=>x&&!STOP.has(x)&&!/^\d+$/.test(x)).join(" ")}
function match(i,name){let a=core(i.name),b=core(name);if(i.name==="Berliner Auswahl")return b.includes("berliner")&&!/\b(?:4|6|8|12)\s*st\b/.test(n(name));if(i.name==="Donut Auswahl")return b.includes("donut")&&!b.includes("crodot")&&!/\b(?:4|6|8|12)\s*st\b/.test(n(name));if(i.name==="Laugenkranz Auswahl")return b.includes("laugenkranz");return a&&a===b}
function weight(name){let m=[...String(name||"").matchAll(/(\d+(?:[.,]\d+)?)\s*(kg|g)\b/gi)].at(-1);if(!m)return 0;let x=+m[1].replace(",",".");return m[2].toLowerCase()==="kg"?x:x/1000}
function qFor(i,r){let q=+r.qty||0,k=weight(i.name);return k&&/(brot|baguette|ciabatta|kruste|kassler|paderborner|laib)/.test(n(i.name))&&/(^| )kg( |$)/.test(n(r.article_name))?q/k:q}
function easter(y){let a=y%19,b=Math.floor(y/100),c=y%100,d=Math.floor(b/4),e=b%4,f=Math.floor((b+8)/25),g=Math.floor((b-f+1)/3),h=(19*a+b-d-g+15)%30,i=Math.floor(c/4),k=c%4,l=(32+2*e+2*i-h-k)%7,m=Math.floor((a+11*h+22*l)/451),mo=Math.floor((h+l-7*m+114)/31),da=(h+l-7*m+114)%31+1;return `${y}-${String(mo).padStart(2,"0")}-${String(da).padStart(2,"0")}`}
function holiday(d){let y=+d.slice(0,4),e=easter(y),M=new Map([[`${y}-01-01`,"Neujahr"],[add(e,-2),"Karfreitag"],[add(e,1),"Ostermontag"],[`${y}-05-01`,"Tag der Arbeit"],[add(e,39),"Christi Himmelfahrt"],[add(e,50),"Pfingstmontag"],[add(e,60),"Fronleichnam"],[`${y}-10-03`,"Tag der Deutschen Einheit"],[`${y}-11-01`,"Allerheiligen"],[`${y}-12-25`,"1. Weihnachtstag"],[`${y}-12-26`,"2. Weihnachtstag"]]);return{isHoliday:M.has(d),holiday:M.get(d)||"",dayBeforeHoliday:M.has(add(d,1)),dayAfterHoliday:M.has(add(d,-1))}}
async function cred(){let r=await pool().query("SELECT value #>> '{revenueSettings,email}' email,value #>> '{revenueSettings,passwordEncrypted}' enc FROM app_store WHERE key='db'"),email=process.env.GMX_EMAIL||r.rows[0]?.email||"edemircan@gmx.net",pass=process.env.GMX_APP_PASSWORD||"";if(!pass&&r.rows[0]?.enc){let session=process.env.SESSION_SECRET||crypto.createHash("sha256").update(`pep-planer-session:${process.env.DATABASE_URL}`).digest("hex"),key=crypto.createHash("sha256").update(`pep-revenue:${session}`).digest(),p=r.rows[0].enc.split(".");try{let dc=crypto.createDecipheriv("aes-256-gcm",key,Buffer.from(p[0],"base64url"));dc.setAuthTag(Buffer.from(p[1],"base64url"));pass=Buffer.concat([dc.update(Buffer.from(p[2],"base64url")),dc.final()]).toString()}catch{}}if(!pass)throw Error("GMX nicht eingerichtet");return{email,pass}}
function parse(buf){const X=require("xlsx"),w=X.read(buf,{type:"buffer",cellDates:true}),Q=[],D=[];for(const sn of w.SheetNames){let rows=X.utils.sheet_to_json(w.Sheets[sn],{header:1,raw:true,defval:null,blankrows:false}),hi=-1,keys=[];for(let i=0;i<Math.min(80,rows.length);i++){let k=(rows[i]||[]).map(hk);if(new Set(k.filter(Boolean)).size>=4&&k.includes("qty")){hi=i;keys=k;break}}if(hi<0)continue;let c={article:"",name:"",date:""};for(const row of rows.slice(hi+1)){let o={};keys.forEach((k,i)=>{if(k&&o[k]===undefined)o[k]=row[i]});let no=article(o.article),name=String(o.name||"").trim(),date=iso(o.date),sl=slot(o.slot);if(!no&&o.article){no=article(o.article);if(!name)name=String(o.article).replace(no,"").trim()}if(no)c.article=no;else no=c.article;if(name)c.name=name;else name=c.name;if(date)c.date=date;else date=c.date;if(!no||!date||/gesamt|ergebnis|summe/i.test(name))continue;let x={date,slot:sl,no,name:name||no,qty:num(o.qty),revenue:num(o.revenue),writeoff:Math.abs(num(o.writeoff)),action:num(o.action)};(sl?Q:D).push(x)}}return{Q,D}}
async function importMail(){await init();const{ImapFlow}=require("imapflow"),{simpleParser}=require("mailparser"),c=await cred(),client=new ImapFlow({host:"imap.gmx.net",port:993,secure:true,auth:{user:c.email,pass:c.pass},logger:false});let files=0,rows=0;try{await client.connect();let lock=await client.getMailboxLock("INBOX");try{let u=await client.search({since:new Date(Date.now()-3*86400000)},{uid:true});for(const id of u.slice(-80).reverse()){let m=await client.fetchOne(id,{envelope:true,source:true},{uid:true});if(!m?.source)continue;let x=await simpleParser(m.source);if(!(x.from?.value||[]).some(z=>String(z.address||"").toLowerCase()===(process.env.REVENUE_REPORT_SENDER||"NoReplyBerichtsexport@edeka.de").toLowerCase()))continue;for(const a of x.attachments||[]){if(!/\.xlsx?$/i.test(a.filename||""))continue;let sid=crypto.createHash("sha256").update(`${x.messageId||id}|${a.filename}`).digest("hex");if((await pool().query("SELECT 1 FROM bakery_mail WHERE source_id=$1",[sid])).rowCount)continue;let r;try{r=parse(a.content)}catch{continue}if(!r.Q.length&&!r.D.length)continue;await pool().query("BEGIN");try{for(const z of r.Q)await pool().query("INSERT INTO bakery_q15 VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(market_code,sale_date,slot,article_no) DO UPDATE SET article_name=$5,qty=$6,revenue=$7",[MARKET,z.date,z.slot,z.no,z.name,z.qty,z.revenue]);for(const z of r.D)await pool().query("INSERT INTO bakery_daily VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(market_code,sale_date,article_no) DO UPDATE SET article_name=$4,qty=$5,revenue=$6,writeoff=$7,action_qty=$8",[MARKET,z.date,z.no,z.name,z.qty,z.revenue,z.writeoff,z.action]);await pool().query("INSERT INTO bakery_mail(source_id) VALUES($1)",[sid]);await pool().query("COMMIT");files++;rows+=r.Q.length+r.D.length}catch(e){await pool().query("ROLLBACK");throw e}}}}finally{lock.release()}}finally{if(client.usable)await client.logout().catch(()=>{})}return{files,rows}}
async function weather(d){try{let u=`https://api.open-meteo.com/v1/forecast?latitude=${LAT}&longitude=${LON}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=Europe%2FBerlin&start_date=${d}&end_date=${d}`,r=await fetch(u,{signal:AbortSignal.timeout(7000)}),j=await r.json();return{code:j.daily.weather_code[0],max:j.daily.temperature_2m_max[0],min:j.daily.temperature_2m_min[0],rain:j.daily.precipitation_sum[0]}}catch{return{unavailable:true}}}
function wf(w){if(w.unavailable)return 1;let f=1;if(w.max>=28)f-=.02;else if(w.max<=5)f+=.01;if(w.rain>=8)f+=.01;return clamp(f,.97,1.03)}
function mins(s){let[a,b]=String(s).slice(0,5).split(":").map(Number);return a*60+b}function hm(m){return`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`}
function intervals(target,rows,cat){let z=rows.filter(r=>wd(r.sale_date)===wd(target)&&cat.some(i=>match(i,r.article_name))),M=new Map;for(const r of z){let m=mins(r.slot);if(m>=330&&m<=1200)M.set(m,(M.get(m)||0)+(+r.qty||0))}let a=[...M].sort((x,y)=>x[0]-y[0]),tot=a.reduce((s,x)=>s+x[1],0);if(!tot)return[{name:"Morgen",from:"05:30",to:"10:30"},{name:"Mittag",from:"10:30",to:"14:00"},{name:"Nachmittag",from:"14:00",to:"20:00"}];let c=0,b1=630,b2=840,f1=false;for(const[m,q]of a){c+=q;if(!f1&&c/tot>=.45){b1=m+15;f1=true}if(c/tot>=.76){b2=m+15;break}}b1=clamp(Math.round(b1/15)*15,570,690);b2=clamp(Math.round(b2/15)*15,b1+120,930);return[{name:"Morgen",from:"05:30",to:hm(b1)},{name:"Mittag",from:hm(b1),to:hm(b2)},{name:"Nachmittag",from:hm(b2),to:"20:00"}]}
function bi(sl,I){let m=mins(sl),a=mins(I[0].to),b=mins(I[1].to);return m<a?0:m<b?1:2}
async function plan(target){await init();let cat=catalog(),start=add(target,-100),Q=(await pool().query("SELECT sale_date::text,slot::text,article_no,article_name,qty::float8,revenue::float8 FROM bakery_q15 WHERE market_code=$1 AND sale_date>=$2 AND sale_date<$3",[MARKET,start,target])).rows,D=(await pool().query("SELECT sale_date::text,article_no,article_name,qty::float8,revenue::float8,writeoff::float8,action_qty::float8 FROM bakery_daily WHERE market_code=$1 AND sale_date>=$2 AND sale_date<$3",[MARKET,start,target])).rows,I=intervals(target,Q,cat),W=await weather(target),H=holiday(target),closed=wd(target)===0||H.isHoliday,items=[];for(const it of cat){let B=new Map;for(const r of Q.filter(x=>match(it,x.article_name))){let x=B.get(r.sale_date)||{q:0,b:[0,0,0]},q=qFor(it,r);x.q+=q;x.b[bi(r.slot,I)]+=q;B.set(r.sale_date,x)}let hist=[...B].filter(([d])=>wd(d)===wd(target)).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,8);if(hist.length<3)hist=[...B].sort((a,b)=>b[0].localeCompare(a[0])).slice(0,16);let base=hist.length?median(hist.slice(0,6).map(x=>x[1].q)):0,dd=D.filter(x=>match(it,x.article_name)&&wd(x.sale_date)===wd(target)).slice(-6),rev=dd.reduce((s,x)=>s+Math.max(0,x.revenue||0),0),wo=dd.reduce((s,x)=>s+Math.max(0,x.writeoff||0),0),ratio=rev+wo?wo/(rev+wo):0,total=closed?0:Math.ceil(base*(1+clamp(.05-.35*ratio,.01,.05))*(H.dayBeforeHoliday?1.03:H.dayAfterHoliday?1.01:1)*wf(W)),s=[0,0,0];for(const[,x]of hist.slice(0,6))for(let j=0;j<3;j++)s[j]+=x.b[j];let st=s.reduce((a,b)=>a+b,0),share=st?s.map(x=>x/st):it.type==="Auftauplan"?[.7,.2,.1]:[.58,.27,.15],raw=share.map(x=>x*total),b=raw.map(Math.floor),left=total-b.reduce((a,x)=>a+x,0);raw.map((v,j)=>({j,f:v-Math.floor(v)})).sort((a,b)=>b.f-a.f).slice(0,left).forEach(x=>b[x.j]++);items.push({no:it.no,name:it.name,type:it.type,program:it.program,total,buckets:b,history:hist.length,risk:ratio>=.08?"hoch":ratio>=.035?"mittel":"niedrig"})}let payload={version:"auto-v1",planDate:target,intervals:I,items,totals:{all:items.reduce((s,x)=>s+x.total,0),Backplan:items.filter(x=>x.type==="Backplan").reduce((s,x)=>s+x.total,0),Brotplan:items.filter(x=>x.type==="Brotplan").reduce((s,x)=>s+x.total,0),Auftauplan:items.filter(x=>x.type==="Auftauplan").reduce((s,x)=>s+x.total,0)}},source=Q.map(x=>x.sale_date).sort().at(-1)||null,ctx={...H,closed,weatherFactor:wf(W)};await pool().query("INSERT INTO bakery_plans VALUES($1,$2,now(),$3,$4,$5,$6) ON CONFLICT(market_code,plan_date) DO UPDATE SET generated_at=now(),source_max_date=$3,payload=$4,weather=$5,context=$6",[MARKET,target,source,payload,W,ctx]);return{payload,W,ctx,source}}
async function autorun(mode){if(runPromise)return runPromise;runPromise=(async()=>{await init();let now=berlin(),target=mode==="morning"?now.date:add(now.date,1),key=`${mode}:${target}`;if((await pool().query("SELECT 1 FROM bakery_jobs WHERE job_key=$1 AND ran_at>now()-interval '6 hours'",[key])).rowCount)return{ok:true,skipped:true,target};let imported=await importMail().catch(e=>({error:e.message})),p=await plan(target);await pool().query("INSERT INTO bakery_jobs VALUES($1,now()) ON CONFLICT(job_key) DO UPDATE SET ran_at=now()",[key]);return{ok:true,target,imported,total:p.payload.totals.all}})().finally(()=>runPromise=null);return runPromise}
function json(res,s,b){res.writeHead(s,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(b))}function read(req){return new Promise((ok,no)=>{let s="";req.on("data",c=>s+=c);req.on("end",()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})})}
function autoWindow(){let{hour,minute}=berlin();if((hour===20&&minute>=30)||(hour===21&&minute<=10))return"evening";if(hour===5&&minute>=10&&minute<=30)return"morning";return""}
const slots=new Set;function revenueSlot(d,h,m){return((h===8&&[0,15,30,45].includes(m))||(h===9&&m===0))?`${d}-${h}:${m}`:""}
http.createServer=function(listener,...args){return original(async(req,res)=>{try{let u=new URL(req.url||"/","http://localhost"),p=u.pathname;if(p==="/api/bakery/auto"){let m=autoWindow();return json(res,200,m?await autorun(m):{ok:true,skipped:true,reason:"outside-window"})}if(p==="/api/bakery/plans"){await init();let r=await pool().query("SELECT plan_date::text,generated_at,source_max_date::text,payload,weather,context FROM bakery_plans WHERE market_code=$1 ORDER BY plan_date DESC LIMIT 90",[MARKET]);return json(res,200,{ok:true,plans:r.rows})}if(p==="/api/bakery/plan"){await init();let d=String(u.searchParams.get("date")||""),r=await pool().query("SELECT plan_date::text,generated_at,source_max_date::text,payload,weather,context FROM bakery_plans WHERE market_code=$1 AND plan_date=$2",[MARKET,d]);if(!r.rowCount)return json(res,404,{error:"Plan nicht gefunden."});let a=await pool().query("SELECT article_no,interval_index,planned_qty,actual_qty,done_at FROM bakery_actuals WHERE market_code=$1 AND plan_date=$2",[MARKET,d]);r.rows[0].actuals=a.rows;return json(res,200,{ok:true,plan:r.rows[0]})}if(p==="/api/bakery/actual"&&req.method==="POST"){await init();let x=await read(req);await pool().query("INSERT INTO bakery_actuals VALUES($1,$2,$3,$4,$5,$6,now()) ON CONFLICT(market_code,plan_date,article_no,interval_index) DO UPDATE SET planned_qty=$5,actual_qty=$6,done_at=now()",[MARKET,x.date,String(x.articleNo),+x.intervalIndex,Math.max(0,Math.round(+x.plannedQty||0)),Math.max(0,Math.round(+x.actualQty||0))]);return json(res,200,{ok:true})}if(p==="/api/jobs/revenue-import"){let z=berlin(),sl=revenueSlot(z.date,z.hour,z.minute);if(!sl||slots.has(sl))return json(res,200,{ok:true,skipped:true});slots.add(sl)}}catch(e){console.error("wrapper",e);if(!res.headersSent)return json(res,500,{error:e.message})}return listener(req,res)},...args)};
const{startServer}=require("./server-core");startServer().catch(e=>{console.error(e);process.exit(1)});
